<?php
/********* 首页配置 *********/
$index_config = array (
  'ab6_img' => 'uploadfiles/images/201406181440333948.gif',
  'ab1_img' => 'uploadfiles/images/201406181440337822.gif',
  'ab2_img' => 'uploadfiles/images/201406181440336617.gif',
  'ab3_img' => 'uploadfiles/images/201406181440339794.gif',
  'ab4_img' => 'uploadfiles/images/201406181440335253.gif',
  'ab5_img' => 'uploadfiles/images/201406181440339383.gif',
  'index1_img' => 'uploadfiles/images/201406051752417091.jpg',
  'index2_img' => 'uploadfiles/images/201406051752515207.jpg',
  'index3_img' => 'uploadfiles/images/201406051752519746.jpg',
  'ab1_title' => 'web design1',
  'case_class' => '快消品#服装行业#建筑行业#广告公司#网络公司',
  'time_class' => '2012#2013#2014',
  'ab1_link' => './about.php?cid=17',
  'ab2_title' => 'web design2',
  'ab2_link' => './about.php?cid=18',
  'ab3_title' => 'web design3',
  'ab3_link' => './about.php?cid=19',
  'ab4_title' => 'web design4',
  'ab4_link' => './about.php?cid=20',
  'ab5_title' => 'web design5',
  'ab5_link' => './about.php?cid=21',
  'ab6_title' => 'web design6',
  'ab6_link' => './about.php?cid=22',
  'case_url' => 'Shanghai  Qiuchuang Science and Technology Co., Ltd. is a professional corporate website design and Internet software development of the modern high-tech joint-stock enterprise, business scope includes: online one-stop service (domain name registration, web hosting, managed hosting, dedicated hosting, business offices,corporate website planning, website construction, flash',
  'wi_title' => 'IMPROVING CUSTOMER
BRAND IMAGE',
  'wi_desc' => 'Based on Shanghai service hundreds of well-known 
brand 5 thousands of domesticand foreign enterprises',
  'wc_title' => 'GET IN TOUCH WITH US',
  'wc_desc' => 'SEE HOW YOUR BUSINESS CAN BENEFIT WITH 
BLUE FOUNTAIN MEDIA ON YOUR TEAM.',
  'ad3_url' => '',
  'ad3_img' => NULL,
  'ad4_url' => '',
  'ad4_img' => NULL,
  'ad5_url' => '',
  'ad5_img' => NULL,
  'ad6_url' => '',
  'ad6_img' => NULL,
  'ad_video' => NULL,
  'video_url' => NULL,
  'about_title' => '',
  'about_brief' => '',
  'index_qq' => '',
  'index_email' => '',
  'index_address' => '',
  'agency_title' => '',
  'agency_img' => NULL,
  'agency_brief' => '',
  'especia_title' => '',
  'especia_img' => NULL,
  'especia_brief' => '',
  'waizi_title' => '',
  'waizi_img' => NULL,
  'waizi_brief' => '',
  'service_title' => '',
  'service_img' => NULL,
  'service_brief' => '',
  'phone_1' => '',
  'phone_2' => '',
  'phone_3' => '',
  'neizi_img_url' => NULL,
  'licai_img_url' => NULL,
);
?>